### ISSUE TITLE
Investigate node function on PKS crash loop

### ISSUE THREAD

**Issue by scothis** [projectriff/node-function-invoker#113]
The node function is consistently entering a crash loop when running on PKS. It works on every other k8s runtime that we test.

See https://dev.azure.com/projectriff/projectriff/_build/results?buildId=2750&view=logs&jobId=88362a0d-4bdb-5566-6120-ca9d0da39f74&taskId=99c6fbac-d6aa-5ac3-890e-a553abc603e4&lineStart=61&lineEnd=62&colStart=1&colEnd=1

**Comment by trisberg** [comment]
This is the error I saw when running on PKS/vSphere:

```
default/square-deployer-964sb-8b4c779b6-5r4sq[handler]: E1028 18:32:19.021680203      15 server_chttp2.cc:40]        {"created":"@1572287539.021649377","description":"No address added out of total 1 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1572287539.021645968","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_custom.cc","file_line":404,"referenced_errors":[{"created":"@1572287539.021640246","description":"Failed to initialize UV tcp handle","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":72,"grpc_status":14,"os_error":"address family not supported"}]}]}
```

**Comment by sbawaska** [comment]
please revert https://github.com/projectriff/fats/commit/070a35607c5706115ff29316d9eac673886c25a5 when this issue is fixed

**Comment by fbiville** [comment]
I think we're stuck until https://github.com/grpc/grpc-node/issues/1209 is solved.
