### ISSUE TITLE
Error handling does not currently comply to the invoker specification

### ISSUE THREAD

**Issue by fbiville** [projectriff/node-function-invoker#137]
The invoker specification details error conditions [here](https://github.com/projectriff/invoker-specification/blob/3ddb2ac1fe521f01dad3f0b6c57a9f9ab13a6f89/streaming.md#stream-completion-and-error-conditions).

What is currently missing:

 - `When an invoker receives the error stream completion signal on its input stream, it MUST propagate that error termination to all of the function input streams.`
 - `When a function emits an error completion signal on one of its several output streams, an invoker MUST immediately forward that signal back to the main output stream.`
 - when a function throws _when invoked_ (as opposed to when receiving data [see this point below]), the error should be propagated to the gRPC output stream (this is part of the spec yet but should be)

What is currently implemented and should be removed:

- the streaming pipeline currently terminates if any of the input unmarshaller errors (see [this](https://github.com/projectriff/node-function-invoker/blob/2883a0cf551be1f58d1605484ebf285d1b47b268/lib/streaming-pipeline.js#L162) and [this](https://github.com/projectriff/node-function-invoker/blob/2883a0cf551be1f58d1605484ebf285d1b47b268/lib/streaming-pipeline.js#L45))

What is currently unclear:

 - how to handle functions doing something like (with fictional map operator):
```js
inputStream
    .pipe(map(() => throw new Error('yolo')))
    .pipe(outputStream)
```

**Comment by scothis** [comment]
What is `map()`?

**Comment by fbiville** [comment]
> What is `map()`?
In Nodeland, this is a [`Transform`](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_class_stream_transform) stream who applies a given function to every message it receives.

**Comment by scothis** [comment]
I disagree with each of these bullet points being in the spec. The invoker spec should define the protocol for communicating with an invoker. It should have no bearing on the execution of that invoker. An invoker must be free to implement any developer experience it sees fit.

That said, I do think implementing these are a good idea for the node function invoker.

**Comment by jldec** [comment]
@fbiville i suggest renaming the issue to "error handling improvements" and mention that the details of the spec are in flux. I think all those enhancements make sense. There may be a few additional edge cases e.g. when the exported function throws (vs. the function triggered by on('data'...)
