### ISSUE TITLE
Missing header makes invocation hang

### ISSUE THREAD

**Issue by kapolos** [projectriff/node-function-invoker#152]
Invoking a Node function without `-H 'Content-Type: application/json'` makes it hang.

```
curl http://knative-square.default.svc.cluster.local -d 2
```

hangs with no repsonse.

In contrast, the Command Runtime returns normally.

```
curl http://knative-greet.default.svc.cluster.local -d 2
```

**Comment by fbiville** [comment]
Thanks for the report @kapolos.

I think you may have been bitten by https://github.com/projectriff/node-function-invoker/issues/133.

The [streaming adapter](https://github.com/projectriff/streaming-http-adapter/), which acts as a HTTP proxy in front of streaming invokers (Node, Java but **not** Command), [defaults the Content-Type and the Accept headers](https://github.com/projectriff/streaming-http-adapter/blob/master/pkg/proxy/proxy.go#L86-L93).

So your payload ends up being interpreted as `application/octet-stream`, and the conversion may then fail. Once the above issue is fixed (very soon), the request will not hang and you will see an explicit error.

In order for me to confirm this hypothesis, could you please re-run `curl` with the verbose option, tail the logs of the `function` container of the Knative adapter pod and share them here?

Thanks a lot!

**Comment by fbiville** [comment]
Let me first find a non-obtrusive way to get verbose logs from the Node invoker (i.e. expose `NODE_DEBUG='riff'` when the adapter is started in the cluster).

**Comment by fbiville** [comment]
Closing this as this seems to duplicate #133. Feel free to reopen it if you do not think so.
