### ISSUE TITLE
Lifecycle methods don't seem to work properly

### ISSUE THREAD

**Issue by kapolos** [projectriff/node-function-invoker#189]
This is the file I used to test the lifecycle methods:

```
const instanceId = Math.round(Math.random() * 10000)
let invocationCount = 0

module.exports.$init = () => {
  console.log('Init is running')
}

module.exports = async () => {
  invocationCount++
  console.log(instanceId, invocationCount)
}

module.exports.$destroy = async () => {
  console.log('Destroy is running')
}

```

This is the result, which seems to be inconsistent with the documentation.

![image](https://user-images.githubusercontent.com/10794126/79809505-4deed280-8379-11ea-92ab-e4b0135efe72.png)

Environment:

Node 12
`riff version 0.6.0-snapshot (187e783565eb69c76af017d1d9e461432350a51a)`

**Comment by fbiville** [comment]
The `$init` hook must be set after the function, else it will just be overwritten.

I have not been able to reproduce this behavior:
```
Starting streaming-http-adapter 0.5.4-snapshot 714274131c45ef31a9ea2ff35430ae90f840feb5

Calling $init hook (if any)
Init is running
$init hook successfully completed (or skipped if none)
Ready to process signals
New invocation started # <- first request
Promoting request-reply function to streaming function
Streaming pipeline initialized
Input signal received
Start signal with: output content types: */*, input names: [in], output names: [out]
Wiring 1 input stream(s)
Wiring 1 output stream(s)
Ready to process data
Input signal received
Forwarding data for input #0
628 1
Ending input streams
Last output stream closing: ending destination stream
New invocation started # <- second request
Promoting request-reply function to streaming function
Streaming pipeline initialized
Input signal received
Start signal with: output content types: */*, input names: [in], output names: [out]
Wiring 1 input stream(s)
Wiring 1 output stream(s)
Ready to process data
Input signal received
Forwarding data for input #0
628 2
Ending input streams
Last output stream closing: ending destination stream
New invocation started # <- third request
Promoting request-reply function to streaming function
Streaming pipeline initialized
Input signal received
Start signal with: output content types: */*, input names: [in], output names: [out]
Wiring 1 input stream(s)
Wiring 1 output stream(s)
Ready to process data
Input signal received
Forwarding data for input #0
628 3
Ending input streams
Last output stream closing: ending destination stream
Graceful shutdown started # <- kill sent
Calling $destroy hook (if any)
Destroy is running
$destroy hook successfully completed (or skipped if none)
riff-invoker: 32090.772ms
```

**Comment by kapolos** [comment]
@fbiville Thank you for looking into it! 

I noticed that you have `streaming-http-adapter 0.5.4-snapshot` while I have `0.5.1-snapshot`. I've reinstalled riff on the cluster relatively recently (like 15-20 ago) by following the 0.6.x instructions (removed everything that came with 0.5.x before installing). Is it normal to have this difference or perhaps is my installation somehow not as it should be? Is there a way for me to verify the validity of the installation?

I tested with the init declared after the main function and it shows up but on every invocation like the destroy method.

![image](https://user-images.githubusercontent.com/10794126/79870488-be363c00-83eb-11ea-9dc6-523afd3a190c.png)

This is my build script:

```
#!/usr/bin/env bash

NS=test
FN=test-lifecycles

set -ex

# Sanity check
FILE=$(readlink -f host_build.sh)
[ ! -f "$FILE" ] && echo "Invalid directory" && exit

# Prepare
rm -rf stage/*
cp -r src stage/
cp index.js package.json yarn.lock stage/
cd stage

riff function delete $FN -n $NS || true

riff knative deployer delete $FN -n $NS || true

# Fails inside container
riff function create $FN \
  --artifact index.js \
  --local-path . \
  --image container-registry-1.foo.bar/foobar/$FN \
  --namespace $NS

riff knative deployer create $FN \
  --function-ref $FN \
  --min-scale 1 \
  --max-scale 3 \
  --namespace $NS \
  --tail

riff knative deployer list -n $NS | grep $FN

riff knative deployer list -n $NS | grep $FN | awk '{ print $4 }'

# clean up
cd ..
rm -rf stage/*
```

I've port forwarded `envoy-internal` to my dev machine, set up the respective domain in my `hosts` file. 

![image](https://user-images.githubusercontent.com/10794126/79872382-65b46e00-83ee-11ea-9577-2fec0b7a73fa.png)

Then I make post requests like this: 

```
curl --request POST \
  --url http://test-lifecycles.test:9501/ \
  --header 'content-type: application/json' \
  --header 'host: test-lifecycles.test' \
  --data '{}'
```

As an aside, how did you get that neat list of events? Is there a flag I can use to see the respective events on my end?

**Comment by scothis** [comment]
The latest snapshots that would be installed from the projectriff.io docs don't yet have the updated invokers/adapter. I'll try to get that done today (CI is being finicky), but in the mean time, you can manually update the function builder to use the latest builder snapshot.

```
kubectl edit clusterbuilders.build.pivotal.io riff-function
```

Set `.spec.image` to `projectriff/builder:0.6.0-snapshot`

**Comment by scothis** [comment]
If it helps, you can find us on slack http://slack.projectriff.io

**Comment by fbiville** [comment]
> As an aside, how did you get that neat list of events? Is there a flag I can use to see the respective events on my end?

You can run `riff knative deployer create` with `--env NODE_DEBUG="riff"`.

**Comment by kapolos** [comment]
Migrating to `projectriff/builder:0.6.0-snapshot` solved the problem, it now works as expected. Thank you very much, see you on Slack!

**Comment by scothis** [comment]
Fresh snapshot installs will get the new invokers now. Getting a clean CI run with GitHub down was fun.
