### ISSUE TITLE
Handle non-utf8 encodings in gRPC invoker

### ISSUE THREAD

**Issue by scothis** [projectriff/node-function-invoker#31]
The gRPC invoker currently ignores the charset defined in the `Content-Type` header. We should attempt to use the declared charset when converting the node Buffer to a string. We'll likely need to limit the acceptable charsets since the Buffer type only supports a few encodings.

See https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings

**Comment by jldec** [comment]
This is a followup for #30

**Comment by scothis** [comment]
no need with #65
