### ISSUE TITLE
build.sh assumes that jq is installed

### ISSUE THREAD

**Issue by jldec** [projectriff/node-function-invoker#35]
If jq is not installed, running `./build.sh` produces the following error.

```
Successfully tagged projectriff/node-function-invoker:latest
Error parsing reference: "projectriff/node-function-invoker:" is not a valid repository/tag: invalid reference format
```

**Comment by scothis** [comment]
`jq` allows us to have a single source of truth for the current version.

If you have a better way to grab a key out of a JSON file we can use that, otherwise, I'd hedge towards documenting the requirement. If we wanted to get silly, we could use `jq` via `docker run`

**Comment by jldec** [comment]
i'd be ok with the extra install requirement
sed is less robust but doesn't require another install
defer to your taste on this :)

```sh
version=${1:-`sed -n -e 's/  "version": "\(.*\)",/\1/p' package.json`}
```
