### ISSUE TITLE
The node version used in CI should be aligned to the one used by the Node buildpack

### ISSUE THREAD

**Issue by fbiville** [projectriff/node-function-invoker#86]
https://github.com/projectriff/node-function-invoker/pull/85 passed although it initially contained code that assumed `TextDecoder` and `TextEncoder` were globally available.
This is true for Node version >= 11.

However, the Node buildpack currently pulls Node 10.15.3 and these classes needs an explicit import, else the Node buildpack build fails.

Making sure the Node version used in CI here is the same as the buildpack would avoid this kind of late errors.

**Comment by scothis** [comment]
CI is running with Node 10. Are the Node 11 bits covered by tests?

https://github.com/projectriff/node-function-invoker/blob/e50150b7a914eee6cfa9332f643c2daa5d61b803/.travis.yml#L2

**Comment by fbiville** [comment]
I guess it was not at that point. My bad.
