### ISSUE TITLE
Support user extensibility of content marshalers

### ISSUE THREAD

**Issue by scothis** [projectriff/node-function-invoker#87]
Currently the invoker only supports json, plain text, bytes and form encoded data. It may be desirable for a function author to use other standard content types or custom content types for their business domain.

The function author should be able to provide new marshalers, similar to the [built in marshalers](https://github.com/projectriff/node-message/blob/master/lib/message.js#L19-L61), on the exported function similar to `$init`. At runtime, the invoker should merge the built in marshalers with the function provided marshalers.

**Comment by scothis** [comment]
Down the road I'd like to handle all `+json` mime types equally. In a previous life I [created a more feature rich mime registry](https://github.com/cujojs/rest/blob/master/mime/registry.js#L102).

**Comment by fbiville** [comment]
I came with this API proposal a few months ago: https://github.com/fbiville/marshmallow.
Custom (un)marshallers could be declared directly as function attributes, the same way hooks or (soon-to-be removed) argument transformers are.

**Comment by scothis** [comment]
We should make sure the interface is appropriate for vendor extensibility as much as user extensibility. For example, a buildpack may want to add a marshaler to all functions without user intervention.
