### ISSUE TITLE
Support for application/cloudevents+json

### ISSUE THREAD

**Issue by joshwlewis** [projectriff/node-function-invoker#88]
Handily, this invoker already supports CloudEvents' [binary content mode](https://github.com/cloudevents/spec/blob/master/http-transport-binding.md#31-binary-content-mode). Since the binary mode leaves the `Content-Type` header unchanged, this invoker will procede to deserialize based on that header, meaning `application/json` encoded cloudevents will be turned into JS object payloads.

However, for folks using CloudEvents' [structured content mode](https://github.com/cloudevents/spec/blob/master/http-transport-binding.md#32-structured-content-mode), this invoker will reject the request. That's because it uses a `Content-Type` header of `application/cloudevents+json`. Given that Knative eventing is choosing to adopt CloudEvents, there may be good reason to support this mode in Riff.

As a super simple implementation, `application/cloudevents+json` could be treated the exact same way as `application/json` (meaning use`JSON.parse` and `JSON.stringify`), which would allow the user to read the CloudEvent envelope and the data contained within.

**Comment by dprotaso** [comment]
@scothis should this issue be closed given #89 merged?

Probably worth opening a separate issue for https://github.com/projectriff/node-function-invoker/pull/89#issuecomment-523678042

> Down the road I'd like to handle all +json mime types equally.
